### PR TITLE
add schedule yaml

### PR DESCRIPTION
**Pull request by JessicaS11**
Adds a [tentative] schedule to the website based on the GitHub project KanBan board.

### CODE REVIEW

**Comment by JessicaS11** [comment]
@jomey @scottyhq Is it failing to build because of the blank resources entries (e.g. line 14)? I was hoping to leave that infrastructure in for filling in as we go. Do I need to add spaces/empty lists to each one?

**Comment by JessicaS11** [comment]
Current leads who are on the schedule but not the website are: @mikala-nsidc Tom Neumann @bessoh2

**Comment by scottyhq** [comment]
Thanks @JessicaS11 ! 

> UPDATE: It's whether or not the listed lead is in the organizing team list 

Good to know! I guess that is the drawback of the otherwise convenient 'modal'-pop up window with the team.yaml information that automatically makes it into the schedule. I wonder if it would be easy to make the modal link optional? Perhaps @jomey 's changes here are a guide for how to accomplish that with the index.html file https://github.com/ICESAT-2HackWeek/website2022/pull/15/files#diff-7df37eaad2c3df776cd5200cf38ef3194b3ad9222950a3f1cec40cb2ebb15ac5 ...

``` 
leads:
  - []
 ```
I think this translates to an empty list in a list `leads: [[]]`

**Review by scottyhq — APPROVED** [review]
Seems good to merge! we can always update going forward, and perhaps open an issue for in the template repository for making instructors being present in team.yml optional

**Comment by jomey** [comment]
The way the template is setup right now is to either have leads or leave out the key entirely:
https://github.com/ICESAT-2HackWeek/website2022/blob/a66ad235d220adfd90e5e94e27cb9dc3c0118ad0/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/index.html#L384

So instead of having an empty array, just remove the line completely.

**Pull request merged**
