### PR TITLE
Fix QAQC.yml workflow to fail given errors

### PR DESCRIPTION
**Pull request by scottyhq**
Follow up for #88, this improves the QAQC workflow to not pass if there are: 
1. spellcheck errors
2. non-cleaned notebooks not listed in _config.yml exclude_patterns
3. broken links

### CODE REVIEW

**Comment by scottyhq** [comment]
After merging this I'll follow up to get the following notebooks with rendered outputs on the website, then create a tag and release: 
* https://icesat-2.hackweek.io/tutorials/geospatial/geospatial-advanced.html
* https://icesat-2.hackweek.io/tutorials/DataVisualization/Visualization_Earth_Engine_geemap_IS2_HW_2022.html
* https://icesat-2.hackweek.io/tutorials/DataIntegration/dataintegration-1.html

**Comment by scottyhq** [comment]
dataintegration-2.ipynb currently failing with an NSIDC error: 
```
Total number of data order requests is  1  for  11  granules.
Data request  1  of  1  is submitting to NSIDC
order ID:  5000002970125
Initial status of your order request at NSIDC is:  processing
Your order status is still  processing  at NSIDC. Please continue waiting... this may take a few moments.
Your order is:  complete_with_errors
NSIDC provided these error messages:
['Some granules failed. 6 granules reported processing messages.',
 'PT6.123S',
 'ICESAT2',
 '228809321:InternalError-Cannot run program '
 '"/usr/ecs/OPS/CUSTOM/utilities/ICESat2ToolAdapter.py": error=24, Too many '
 'open files',
 '228906565:InternalError-Cannot run program '
 '"/usr/ecs/OPS/CUSTOM/utilities/ICESat2ToolAdapter.py": error=24, Too many '
 'open files',
 '228882526:InternalError-Cannot run program '
 '"/usr/ecs/OPS/CUSTOM/utilities/ICESat2ToolAdapter.py": error=24, Too many '
 'open files',
 '228898773:InternalError-Cannot run program '
 '"/usr/ecs/OPS/CUSTOM/utilities/ICESat2ToolAdapter.py": error=24, Too many '
 'open files',
 '228960877:InternalError-Cannot run program '
 '"/usr/ecs/OPS/CUSTOM/utilities/ICESat2ToolAdapter.py": error=24, Too many '
 'open files',
 '228951485:InternalError-Cannot connect to the specified SUBAGENT. Please '
 'contact user services.']
Your order is: complete_with_errors
NSIDC returned these messages
['228809321:InternalError-Cannot run program '
 '"/usr/ecs/OPS/CUSTOM/utilities/ICESat2ToolAdapter.py": error=24, Too many '
 'open files',
 '228906565:InternalError-Cannot run program '
```

**Comment by jomey** [comment]
Any idea on why the OS X pipeline is unhappy?

**Review by jomey — APPROVED** [review]

**Comment by jomey** [comment]
Just for reference, I use the `jupyter nbconvert` command locally before committing notebooks
Simple bash wrapper here: https://github.com/jomey/environment-setups/blob/master/common/clear_nbs.bash

**Comment by scottyhq** [comment]
> Any idea on why the OS X pipeline is unhappy? 

I'm not sure. The logs are not so informative when it comes to cache problems. I'm a bit wary of a single shared cache across different platforms (effective we just mount a folder created on a linux machine onto mac, so i wouldn't be surprised if jupyterbook gets confused with file permissions, etc). Also, imagine a notebook code cell that has `!lscpu` which will give different outputs depending on the host machine... We'll see if re-executing and bumping the cache key passes on both in a followup PR...

**Pull request merged**
