### PR TITLE
Render all notebooks

### PR DESCRIPTION
**Pull request by scottyhq**
Renders or executes all notebooks on website prior to zenodo release

### CODE REVIEW

**Review by jomey — APPROVED** [review]

**Comment by jomey** [comment]
Should we also add a link to the Zenodo ID on the index page for the JupyterBook?

**Comment by scottyhq** [comment]
> Should we also add a link to the Zenodo ID on the index page for the JupyterBook? 

Yeah, most people probably interact with the website as opposed to the repository, so I think it's a good idea. But there is a chicken and egg issue of needing to create a release -> DOI -> then add DOI to website... but will do!

**Comment by scottyhq** [comment]
Interestingly, re-executing notebooks that were previously cached surfaced errors with Cloud-access credentials (#120), and also icepyx code that doesn't specify a version and has hard-coded filenames will eventually error (cc @JessicaS11, although I'm sure you're already aware of this situation :) :

```
region_iceland = ipx.Query(
    product="ATL11",
    spatial_extent=[-28.0, 62.0, -10.0, 68.0],  # minlon, minlat, maxlon, maxlat
    tracks=["1358"],  # Get one specific track only
)
```

```
    -  filename_or_obj="/tmp/processed_ATL11_135803_0311_004_01.h5",
    + filename_or_obj="/tmp/processed_ATL11_135803_0313_005_01.h5",
```

**Comment by weiji14** [comment]
Thanks for the ping @scottyhq. Yes, probably should have set the version on that ATL11 dataset, but the plot doesn't really change much so should be fine :upside_down_face:

Oh, and FYI, I've triggered a full archive of the Jupyter Book using WaybackMachine yesterday (13 April 2022) using the 'Save outlinks' option at https://web.archive.org/save (need a Wayback Machine account to have it automatically follow the hyperlinks).

image

We could trigger another snapshot archive once #121 is merged perhaps, assuming there won't be any more changes to the website.

**Comment by scottyhq** [comment]
> Access link is at https://web.archive.org/web/20220413153630/https://icesat-2.hackweek.io/intro.html. 

Cool! Didn't know about this. 

> assuming there won't be any more changes to the website. 

Initially we had a vision for the jupyterbook being a resource that people could continue to modify and add to (thus the release and zenodo DOI for the snapshot in time), but the reality seems to be that development ceases after the event and we all move onto other things ;)

**Comment by weiji14** [comment]
Yeah, it's still nice though to have a tagged release and DOI snapshot. Do you think we'll be using the website (https://icesat-2.hackweek.io) next year? I'm assuming that there will be a new website2023 repo, and was wondering whether the old material would just disappear or be under another link like https://icesat-2.hackweek.io/2022.

**Pull request merged**
