### PR TITLE
Preliminary - Update git; add setup check repo URL.

### PR DESCRIPTION
**Pull request by jomey**
Also update the screenshot to the latest version.

### CODE REVIEW

**Review by danshapero — APPROVED** [review]

**Comment by scottyhq** [comment]
I'm not sure why the CI didn't run here...

**Comment by jomey** [comment]
> I'm not sure why the CI didn't run here...

I pushed again while it was running, but that shouldn’t hurt things? At least would baffle me.

**Comment by scottyhq** [comment]
could it be due to https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification ?...

**Review by scottyhq — APPROVED** [review]
thanks @jomey i opened a separate issue to track down the github actions running

**Pull request merged**
