### PR TITLE
Tutorial - git; Update URLs to create a fork for personal notes.

### PR DESCRIPTION
**Pull request by jomey**
Was still only showing placeholders

### CODE REVIEW

**Comment by scottyhq** [comment]
is there an error in our substitution setup? https://github.com/ICESAT-2HackWeek/website2022/blob/45a2d4a758001bde9861299510e384105666ca57/book/_config.yml#L12

**Comment by scottyhq** [comment]
Looks like the problem is substitutions within backticks: https://github.com/ICESAT-2HackWeek/website2022/blob/45a2d4a758001bde9861299510e384105666ca57/book/tutorials/jupyter.md?plain=1#L173-L176

**Comment by jomey** [comment]
> > is there an error in our substitution setup?
> > https://github.com/ICESAT-2HackWeek/website2022/blob/45a2d4a758001bde9861299510e384105666ca57/book/_config.yml#L12
> 
> Good question. Are they case sensitive?

Apparently they don't work in code blocks or when using backticks

**Review by scottyhq — APPROVED** [review]
Feel free to merge and we can sort out substitutions in code blocks later

**Pull request merged**
