### PR TITLE
Ab/cloud computing tutorial

### PR DESCRIPTION
**Pull request by abarciauskas-bgse**

### CODE REVIEW

**Comment by scottyhq** [comment]
Thanks @abarciauskas-bgse looking really good! Would it be easy for you to reduce the size of the following image:

BIN +6.32 MB book/tutorials/cloud-computing/images/aws-data-centers.png

**Review by scottyhq — CHANGES_REQUESTED** [review]
Thanks @abarciauskas-bgse looking really good! 

* Would it be easy for you to reduce the size of the following image:
BIN +6.32 MB book/tutorials/cloud-computing/images/aws-data-centers.png

* You'll have to push a clean notebook (Kernel-> Restart and Clear Outputs) 

* A couple minor typos too if you wouldn't mind fixing those: https://github.com/ICESAT-2HackWeek/website2022/runs/5592515743?check_suite_focus=true#step:6:24

**Comment by scottyhq** [comment]
About to update the environment to have earthdata=0.2.0, so you can remove the pip install cell. Note that the CI has a built-in .netrc for credentials, for example see https://icesat-2.hackweek.io/tutorials/DataProducts/DataProducts.html#acquiring-atl15-from-nsidc

**Comment by abarciauskas-bgse** [comment]
Removed the earthdata install

**Comment by scottyhq** [comment]
Not sure why but the rioxarray cell is failing with. I added a `skip-execution` cell metadata tag to just skip the execution for rendering on the webpage for now (https://jupyterbook.org/content/metadata.html#jupyter-cell-tags)

```pytb
[0;31mRasterioIOError[0m: '/vsis3/lp-prod-protected/HLSL30.020/HLS.L30.T58KEB.2022077T225645.v2.0/HLS.L30.T58KEB.2022077T225645.v2.0.SZA.tif' not recognized as a supported file format.
RasterioIOError: '/vsis3/lp-prod-protected/HLSL30.020/HLS.L30.T58KEB.2022077T225645.v2.0/HLS.L30.T58KEB.2022077T225645.v2.0.SZA.tif' not recognized as a supported file format.
```

**Review by scottyhq — APPROVED** [review]

**Comment by abarciauskas-bgse** [comment]
I'll take a look thanks Scott!

**Pull request merged**
